services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres # Dockerfile for PostgreSQL
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./vis_phewas:/app/vis_phewas
      - ./mainapp:/app/mainapp
      - ./api:/app/api
      - ./static:/app/staticfiles
      - ./templates:/app/templates
      - ./package.json:/app/package.json
      - ./webpack.config.js:/app/webpack.config.js
      - ./LICENSE:/app/LICENSE
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
