services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./vis_phewas/vis_phewas:/app/vis_phewas/vis_phewas
      - ./vis_phewas/mainapp:/app/vis_phewas/mainapp
      - ./vis_phewas/api:/app/vis_phewas/api
      - ./vis_phewas/templates:/app/vis_phewas/templates
      - ./vis_phewas/package.json:/app/vis_phewas/package.json
      - ./vis_phewas/webpack.config.js:/app/vis_phewas/webpack.config.js
      - ./LICENSE:/app/LICENSE
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./key.pem:/etc/nginx/ssl/key.pem
    depends_on:
      - web

volumes:
  postgres_data:
