services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./vis_phewas/vis_phewas:/app/vis_phewas/vis_phewas
      - ./vis_phewas/mainapp:/app/vis_phewas/mainapp
      - ./vis_phewas/api:/app/vis_phewas/api
      - ./vis_phewas/templates:/app/vis_phewas/templates
      - ./vis_phewas/package.json:/app/vis_phewas/package.json
      - ./vis_phewas/webpack.config.js:/app/vis_phewas/webpack.config.js
      - ./LICENSE:/app/LICENSE
      - staticfiles:/vis_phewas/staticfiles  # Share static files
    ports:
      - "8000:8000"
    env_file:
      - docker.env

volumes:
  postgres_data:
  staticfiles:  # Define the shared volume
