version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vis_phewas_net

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - vis_phewas_net

volumes:
  postgres_data:
  static_volume:

networks:
  vis_phewas_net:
