# Generated by Django 5.0.6 on 2024-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HlaPheWasCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phewas_code', models.FloatField()),
                ('phewas_string', models.CharField(max_length=255)),
                ('cases', models.IntegerField()),
                ('controls', models.IntegerField()),
                ('category_string', models.CharField(max_length=100)),
                ('odds_ratio', models.FloatField()),
                ('p', models.FloatField()),
                ('l95', models.FloatField()),
                ('u95', models.FloatField()),
                ('gene_name', models.CharField(max_length=50)),
                ('maf', models.FloatField()),
                ('a1', models.CharField(max_length=10)),
                ('a2', models.CharField(max_length=10)),
                ('chromosome', models.IntegerField()),
                ('nchrobs', models.IntegerField()),
                ('gene_class', models.IntegerField()),
                ('serotype', models.CharField(max_length=10)),
                ('subtype', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'HLA PheWAS Catalog',
                'verbose_name_plural': 'HLA PheWAS Catalog',
                'db_table': 'hla_phewas_catalog',
            },
        ),
    ]
