# Generated by Django 5.0.6 on 2024-06-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hlaphewascatalog',
            options={'verbose_name': 'HLA PheWAS Catalog', 'verbose_name_plural': 'HLA PheWAS Catalog'},
        ),
        migrations.AlterModelTable(
            name='hlaphewascatalog',
            table='hla_phewas_catalog',
        ),
    ]
