# Generated by Django 5.1 on 2024-08-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_hlaphewascatalog_snp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hlaphewascatalog',
            new_name='hla_phewas__phewas__cf5a4b_idx',
            old_fields=('phewas_string', 'snp'),
        ),
        migrations.RenameIndex(
            model_name='hlaphewascatalog',
            new_name='hla_phewas__categor_2cb8d8_idx',
            old_fields=('category_string', 'phewas_string'),
        ),
        migrations.RenameIndex(
            model_name='hlaphewascatalog',
            new_name='hla_phewas__snp_137310_idx',
            old_fields=('snp', 'odds_ratio'),
        ),
        migrations.RenameIndex(
            model_name='hlaphewascatalog',
            new_name='hla_phewas__snp_b8d730_idx',
            old_fields=('snp', 'p'),
        ),
    ]
